window.NI_DATA = {
  "generated_at": "28/05/2026 23:21",
  "default_view": "total",
  "views": {
    "total": {
      "period": {
        "start": "2026-04-01",
        "end": "2026-05-28",
        "label": "01/04 a 28/05",
        "name": "Período total"
      },
      "stats": {
        "totals": {
          "desqualificado": 106,
          "em_atendimento": 74,
          "qualificado": 6,
          "visita": 10,
          "sem_status": 66,
          "proposta": 1,
          "outros_produtos": 10,
          "nao_momento": 1
        },
        "n_total": 274,
        "perdidos": 106,
        "pct_perda": 38.7,
        "empreend": [
          {
            "emp": "Edf. Greco",
            "corretor": "Rose",
            "leads": 96,
            "atend": 15,
            "visita": 3,
            "qual": 3,
            "proposta": 0,
            "perda": 64,
            "outros": 8,
            "sem": 3,
            "timing": {
              "start": "2026-04-01",
              "end": "2026-05-01",
              "days_active": 57,
              "days_left": -27,
              "start_label": "01/04/26",
              "end_label": "01/05/26",
              "ad_status": "PAUSED",
              "ad_name": "Edf. Greco | Rose",
              "spend": 840.52,
              "spend_shared": false
            }
          },
          {
            "emp": "Casa no Antares",
            "corretor": "Gedson",
            "leads": 33,
            "atend": 7,
            "visita": 1,
            "qual": 1,
            "proposta": 0,
            "perda": 17,
            "outros": 0,
            "sem": 7,
            "timing": {
              "start": "2026-04-01",
              "end": "2026-05-01",
              "days_active": 57,
              "days_left": -27,
              "start_label": "01/04/26",
              "end_label": "01/05/26",
              "ad_status": "PAUSED",
              "ad_name": "Casa no Antares | Gedson",
              "spend": 370.95,
              "spend_shared": false
            }
          },
          {
            "emp": "Jatiúca",
            "corretor": "Adriana",
            "leads": 28,
            "atend": 16,
            "visita": 1,
            "qual": 0,
            "proposta": 0,
            "perda": 8,
            "outros": 1,
            "sem": 2,
            "timing": {
              "start": "2026-04-27",
              "end": "2026-05-27",
              "days_active": 31,
              "days_left": -1,
              "start_label": "27/04/26",
              "end_label": "27/05/26",
              "ad_status": "PAUSED",
              "ad_name": "Jatiúca | Adriana",
              "spend": 557.33,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Guilherme",
            "leads": 27,
            "atend": 10,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 5,
            "outros": 2,
            "sem": 10,
            "timing": {
              "start": "2026-02-27",
              "end": "2026-03-29",
              "days_active": 90,
              "days_left": -60,
              "start_label": "27/02/26",
              "end_label": "29/03/26",
              "ad_status": "PAUSED",
              "ad_name": "Sensia | Nath/Guilherme/Fernanda",
              "spend": 500.84,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Paradise Beach",
            "corretor": "Gedson",
            "leads": 21,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 1,
            "perda": 0,
            "outros": 0,
            "sem": 20,
            "timing": {
              "start": "2026-05-22",
              "end": "2026-06-21",
              "days_active": 6,
              "days_left": 24,
              "start_label": "22/05/26",
              "end_label": "21/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Paradise Beach | Gedson",
              "spend": 182.95,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Fernanda",
            "leads": 17,
            "atend": 2,
            "visita": 1,
            "qual": 0,
            "proposta": 0,
            "perda": 4,
            "outros": 0,
            "sem": 10,
            "timing": {
              "start": "2026-02-27",
              "end": "2026-03-29",
              "days_active": 90,
              "days_left": -60,
              "start_label": "27/02/26",
              "end_label": "29/03/26",
              "ad_status": "PAUSED",
              "ad_name": "Sensia | Nath/Guilherme/Fernanda",
              "spend": 500.84,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Nath",
            "leads": 16,
            "atend": 10,
            "visita": 3,
            "qual": 2,
            "proposta": 0,
            "perda": 1,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-02-27",
              "end": "2026-03-29",
              "days_active": 90,
              "days_left": -60,
              "start_label": "27/02/26",
              "end_label": "29/03/26",
              "ad_status": "PAUSED",
              "ad_name": "Sensia | Nath/Guilherme/Fernanda",
              "spend": 500.84,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Guaxuma",
            "corretor": "Fernanda",
            "leads": 10,
            "atend": 7,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 2,
            "outros": 0,
            "sem": 1,
            "timing": {
              "start": "2026-04-30",
              "end": "2026-05-30",
              "days_active": 28,
              "days_left": 2,
              "start_label": "30/04/26",
              "end_label": "30/05/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Guaxuma | Fernanda",
              "spend": 295.43,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Jorge",
            "corretor": "Tatiana",
            "leads": 8,
            "atend": 3,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 3,
            "outros": 0,
            "sem": 2,
            "timing": {
              "start": "2026-04-01",
              "end": "2026-05-01",
              "days_active": 57,
              "days_left": -27,
              "start_label": "01/04/26",
              "end_label": "01/05/26",
              "ad_status": "PAUSED",
              "ad_name": "Edf. Jorge | Tatiana",
              "spend": 69.41,
              "spend_shared": false
            }
          },
          {
            "emp": "Blend Grand Reserva",
            "corretor": "Stefan",
            "leads": 5,
            "atend": 3,
            "visita": 1,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 1,
            "timing": {
              "start": "2026-05-22",
              "end": "2026-06-21",
              "days_active": 6,
              "days_left": 24,
              "start_label": "22/05/26",
              "end_label": "21/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "VD01",
              "spend": 0.0,
              "spend_shared": false
            }
          },
          {
            "emp": "Blend Grand Reserva",
            "corretor": "Marcos Jr",
            "leads": 4,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 4,
            "timing": {
              "start": "2026-05-22",
              "end": "2026-06-21",
              "days_active": 6,
              "days_left": 24,
              "start_label": "22/05/26",
              "end_label": "21/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "VD01",
              "spend": 0.0,
              "spend_shared": false
            }
          },
          {
            "emp": "Blend Grand Reserva",
            "corretor": "Tati",
            "leads": 3,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 1,
            "outros": 0,
            "sem": 2,
            "timing": {
              "start": "2026-05-22",
              "end": "2026-06-21",
              "days_active": 6,
              "days_left": 24,
              "start_label": "22/05/26",
              "end_label": "21/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "VD01",
              "spend": 0.0,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Ametista",
            "corretor": "Thati",
            "leads": 3,
            "atend": 1,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 1,
            "outros": 0,
            "sem": 1,
            "timing": {
              "start": "2026-05-21",
              "end": "2026-06-20",
              "days_active": 7,
              "days_left": 23,
              "start_label": "21/05/26",
              "end_label": "20/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Ametista | Thati",
              "spend": 23.81,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Horto Boulevard",
            "corretor": "Dimitry",
            "leads": 2,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 2,
            "timing": {
              "start": "2026-05-28",
              "end": "2026-06-27",
              "days_active": 0,
              "days_left": 30,
              "start_label": "28/05/26",
              "end_label": "27/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Horto Boulevard | Dimitry",
              "spend": 11.13,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Aquasol",
            "corretor": "Yohanna",
            "leads": 1,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 1,
            "timing": {
              "start": "2026-05-21",
              "end": "2026-06-20",
              "days_active": 7,
              "days_left": 23,
              "start_label": "21/05/26",
              "end_label": "20/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Aquasol | Yohanna",
              "spend": 41.78,
              "spend_shared": false
            }
          },
          {
            "emp": "JTR Jatiúca",
            "corretor": "Nathalia",
            "leads": 0,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-04-27",
              "end": "2026-05-27",
              "days_active": 31,
              "days_left": -1,
              "start_label": "27/04/26",
              "end_label": "27/05/26",
              "ad_status": "PAUSED",
              "ad_name": "JTR Jatiúca | Nathalia",
              "spend": 41.12,
              "spend_shared": false
            }
          }
        ],
        "motivos": [
          {
            "label": "Não responde / não atende",
            "value": 56,
            "pct": 52.8
          },
          {
            "label": "Motivo ambíguo (revisar)",
            "value": 24,
            "pct": 22.6
          },
          {
            "label": "Sem motivo registrado",
            "value": 11,
            "pct": 10.4
          },
          {
            "label": "Lead repetido",
            "value": 4,
            "pct": 3.8
          },
          {
            "label": "Não gostou do imóvel/região",
            "value": 3,
            "pct": 2.8
          },
          {
            "label": "Valor / orçamento",
            "value": 3,
            "pct": 2.8
          },
          {
            "label": "Lead inválido",
            "value": 3,
            "pct": 2.8
          },
          {
            "label": "Comprou com concorrente",
            "value": 2,
            "pct": 1.9
          }
        ],
        "motivos_total": 106,
        "perdas_by_emp": [
          {
            "emp": "Edf. Greco",
            "corretor": "Rose",
            "perdas": 64,
            "motivos": {
              "Motivo ambíguo (revisar)": 16,
              "Não responde / não atende": 42,
              "Valor / orçamento": 3,
              "Comprou com concorrente": 2,
              "Não gostou do imóvel/região": 1
            }
          },
          {
            "emp": "Casa no Antares",
            "corretor": "Gedson",
            "perdas": 17,
            "motivos": {
              "Sem motivo registrado": 2,
              "Não gostou do imóvel/região": 1,
              "Não responde / não atende": 9,
              "Motivo ambíguo (revisar)": 2,
              "Lead repetido": 3
            }
          },
          {
            "emp": "Jatiúca",
            "corretor": "Adriana",
            "perdas": 8,
            "motivos": {
              "Sem motivo registrado": 8
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Guilherme",
            "perdas": 5,
            "motivos": {
              "Não gostou do imóvel/região": 1,
              "Não responde / não atende": 1,
              "Motivo ambíguo (revisar)": 3
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Fernanda",
            "perdas": 4,
            "motivos": {
              "Lead inválido": 3,
              "Não responde / não atende": 1
            }
          },
          {
            "emp": "Edf. Jorge",
            "corretor": "Tatiana",
            "perdas": 3,
            "motivos": {
              "Lead repetido": 1,
              "Não responde / não atende": 2
            }
          },
          {
            "emp": "Edf. Guaxuma",
            "corretor": "Fernanda",
            "perdas": 2,
            "motivos": {
              "Não responde / não atende": 1,
              "Motivo ambíguo (revisar)": 1
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Nath",
            "perdas": 1,
            "motivos": {
              "Motivo ambíguo (revisar)": 1
            }
          },
          {
            "emp": "Blend Grand Reserva",
            "corretor": "Tati",
            "perdas": 1,
            "motivos": {
              "Motivo ambíguo (revisar)": 1
            }
          },
          {
            "emp": "Edf. Ametista",
            "corretor": "Thati",
            "perdas": 1,
            "motivos": {
              "Sem motivo registrado": 1
            }
          }
        ],
        "series": {
          "labels": [
            "01/04",
            "02/04",
            "03/04",
            "04/04",
            "05/04",
            "06/04",
            "07/04",
            "08/04",
            "09/04",
            "10/04",
            "11/04",
            "12/04",
            "13/04",
            "14/04",
            "15/04",
            "16/04",
            "17/04",
            "18/04",
            "19/04",
            "20/04",
            "21/04",
            "22/04",
            "23/04",
            "24/04",
            "25/04",
            "26/04",
            "27/04",
            "28/04",
            "29/04",
            "30/04",
            "01/05",
            "02/05",
            "03/05",
            "04/05",
            "05/05",
            "06/05",
            "07/05",
            "08/05",
            "09/05",
            "10/05",
            "11/05",
            "12/05",
            "13/05",
            "14/05",
            "15/05",
            "16/05",
            "17/05",
            "18/05",
            "19/05",
            "20/05",
            "21/05",
            "22/05",
            "23/05",
            "24/05",
            "25/05",
            "26/05",
            "27/05",
            "28/05"
          ],
          "total": [
            6,
            3,
            6,
            5,
            10,
            11,
            8,
            6,
            3,
            3,
            1,
            0,
            4,
            1,
            1,
            27,
            3,
            8,
            7,
            7,
            7,
            2,
            6,
            2,
            2,
            5,
            3,
            4,
            12,
            6,
            4,
            0,
            4,
            4,
            8,
            0,
            6,
            5,
            3,
            0,
            4,
            4,
            5,
            2,
            4,
            4,
            3,
            2,
            4,
            1,
            5,
            4,
            1,
            0,
            22,
            1,
            1,
            4
          ],
          "perda": [
            5,
            2,
            4,
            1,
            6,
            7,
            8,
            3,
            2,
            1,
            1,
            0,
            4,
            1,
            1,
            18,
            3,
            4,
            3,
            5,
            5,
            1,
            1,
            1,
            0,
            2,
            1,
            1,
            0,
            2,
            2,
            0,
            2,
            1,
            2,
            0,
            2,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "atend": [
            0,
            0,
            1,
            3,
            4,
            1,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            6,
            0,
            3,
            2,
            0,
            0,
            1,
            5,
            1,
            2,
            1,
            1,
            2,
            10,
            4,
            1,
            0,
            1,
            2,
            4,
            0,
            3,
            2,
            0,
            0,
            1,
            1,
            2,
            1,
            0,
            0,
            1,
            2,
            2,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            0,
            0
          ],
          "visita": [
            0,
            0,
            1,
            0,
            0,
            1,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "qual": [
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "proposta": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0
          ]
        }
      },
      "meta": {
        "spend": 3518.28,
        "impressions": 113926,
        "clicks": 2475,
        "ctr": 2.17,
        "frequency": 3.33,
        "reach": 34183,
        "leads_form": 251,
        "msg_started": 27,
        "total_meta": 278,
        "cpl": 12.66,
        "campaign": {
          "name": "Fundo de Funil | Blend Grand Reserva | 12/05 #TP",
          "status": "ACTIVE",
          "label": "Ativa",
          "start_time": "2026-05-12T19:26:06-0300",
          "objective": "OUTCOME_LEADS"
        }
      },
      "plan": [
        {
          "tag": "Prioridade alta",
          "cls": "crit",
          "icon": "alert",
          "title": "Resgatar a base não respondida",
          "desc": "<b>56 leads</b> do período entraram e não retornaram contato. Antes de aumentar volume, rodar uma cadência de reengajamento e revisar tempo médio de primeiro toque. <b>Maior ponto de alavancagem do mês.</b>"
        },
        {
          "tag": "Time comercial",
          "cls": "proc",
          "icon": "team",
          "title": "Sensia, calibrar distribuição",
          "desc": "3 corretores no mesmo produto. A <b>única proposta do período saiu daqui</b>, o produto tem demanda. Revisar como leads são distribuídos e padronizar a abordagem pode acelerar o ciclo."
        },
        {
          "tag": "Processo",
          "cls": "proc",
          "icon": "process",
          "title": "Padronizar planilhas",
          "desc": "<b>24% dos leads sem status</b> (66 leads). Definir status obrigatório e motivo de perda destrava a próxima camada de análise por produto."
        }
      ]
    },
    "abril": {
      "period": {
        "start": "2026-04-01",
        "end": "2026-04-30",
        "label": "01/04 a 30/04",
        "name": "Abril"
      },
      "stats": {
        "totals": {
          "desqualificado": 93,
          "em_atendimento": 48,
          "qualificado": 5,
          "visita": 7,
          "sem_status": 6,
          "outros_produtos": 9,
          "nao_momento": 1
        },
        "n_total": 169,
        "perdidos": 93,
        "pct_perda": 55.0,
        "empreend": [
          {
            "emp": "Edf. Greco",
            "corretor": "Rose",
            "leads": 90,
            "atend": 14,
            "visita": 3,
            "qual": 3,
            "proposta": 0,
            "perda": 61,
            "outros": 8,
            "sem": 1,
            "timing": {
              "start": "2026-04-01",
              "end": "2026-05-01",
              "days_active": 57,
              "days_left": -27,
              "start_label": "01/04/26",
              "end_label": "01/05/26",
              "ad_status": "PAUSED",
              "ad_name": "Edf. Greco | Rose",
              "spend": 770.85,
              "spend_shared": false
            }
          },
          {
            "emp": "Casa no Antares",
            "corretor": "Gedson",
            "leads": 27,
            "atend": 6,
            "visita": 1,
            "qual": 1,
            "proposta": 0,
            "perda": 16,
            "outros": 0,
            "sem": 3,
            "timing": {
              "start": "2026-04-01",
              "end": "2026-05-01",
              "days_active": 57,
              "days_left": -27,
              "start_label": "01/04/26",
              "end_label": "01/05/26",
              "ad_status": "PAUSED",
              "ad_name": "Casa no Antares | Gedson",
              "spend": 259.34,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Guilherme",
            "leads": 17,
            "atend": 10,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 5,
            "outros": 2,
            "sem": 0,
            "timing": {
              "start": "2026-02-27",
              "end": "2026-03-29",
              "days_active": 90,
              "days_left": -60,
              "start_label": "27/02/26",
              "end_label": "29/03/26",
              "ad_status": "PAUSED",
              "ad_name": "Sensia | Nath/Guilherme/Fernanda",
              "spend": 139.03,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Guaxuma",
            "corretor": "Fernanda",
            "leads": 9,
            "atend": 7,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 2,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-04-30",
              "end": "2026-05-30",
              "days_active": 28,
              "days_left": 2,
              "start_label": "30/04/26",
              "end_label": "30/05/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Guaxuma | Fernanda",
              "spend": 195.53,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Fernanda",
            "leads": 7,
            "atend": 2,
            "visita": 1,
            "qual": 0,
            "proposta": 0,
            "perda": 4,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-02-27",
              "end": "2026-03-29",
              "days_active": 90,
              "days_left": -60,
              "start_label": "27/02/26",
              "end_label": "29/03/26",
              "ad_status": "PAUSED",
              "ad_name": "Sensia | Nath/Guilherme/Fernanda",
              "spend": 139.03,
              "spend_shared": false
            }
          },
          {
            "emp": "Jatiúca",
            "corretor": "Adriana",
            "leads": 7,
            "atend": 6,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 1,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-04-27",
              "end": "2026-05-27",
              "days_active": 31,
              "days_left": -1,
              "start_label": "27/04/26",
              "end_label": "27/05/26",
              "ad_status": "PAUSED",
              "ad_name": "Jatiúca | Adriana",
              "spend": 96.85,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Jorge",
            "corretor": "Tatiana",
            "leads": 6,
            "atend": 1,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 3,
            "outros": 0,
            "sem": 2,
            "timing": {
              "start": "2026-04-01",
              "end": "2026-05-01",
              "days_active": 57,
              "days_left": -27,
              "start_label": "01/04/26",
              "end_label": "01/05/26",
              "ad_status": "PAUSED",
              "ad_name": "Edf. Jorge | Tatiana",
              "spend": 64.91,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Nath",
            "leads": 6,
            "atend": 2,
            "visita": 2,
            "qual": 1,
            "proposta": 0,
            "perda": 1,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-02-27",
              "end": "2026-03-29",
              "days_active": 90,
              "days_left": -60,
              "start_label": "27/02/26",
              "end_label": "29/03/26",
              "ad_status": "PAUSED",
              "ad_name": "Sensia | Nath/Guilherme/Fernanda",
              "spend": 139.03,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Paradise Beach",
            "corretor": "Gedson",
            "leads": 0,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-05-22",
              "end": "2026-06-21",
              "days_active": 6,
              "days_left": 24,
              "start_label": "22/05/26",
              "end_label": "21/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Paradise Beach | Gedson",
              "spend": 0.0,
              "spend_shared": false
            }
          },
          {
            "emp": "JTR Jatiúca",
            "corretor": "Nathalia",
            "leads": 0,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-04-27",
              "end": "2026-05-27",
              "days_active": 31,
              "days_left": -1,
              "start_label": "27/04/26",
              "end_label": "27/05/26",
              "ad_status": "PAUSED",
              "ad_name": "JTR Jatiúca | Nathalia",
              "spend": 34.72,
              "spend_shared": false
            }
          },
          {
            "emp": "Blend Grand Reserva",
            "corretor": "Marcos Jr",
            "leads": 0,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-05-22",
              "end": "2026-06-21",
              "days_active": 6,
              "days_left": 24,
              "start_label": "22/05/26",
              "end_label": "21/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "VD01",
              "spend": 0.0,
              "spend_shared": false
            }
          },
          {
            "emp": "Blend Grand Reserva",
            "corretor": "Stefan",
            "leads": 0,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-05-22",
              "end": "2026-06-21",
              "days_active": 6,
              "days_left": 24,
              "start_label": "22/05/26",
              "end_label": "21/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "VD01",
              "spend": 0.0,
              "spend_shared": false
            }
          },
          {
            "emp": "Blend Grand Reserva",
            "corretor": "Tati",
            "leads": 0,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-05-22",
              "end": "2026-06-21",
              "days_active": 6,
              "days_left": 24,
              "start_label": "22/05/26",
              "end_label": "21/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "VD01",
              "spend": 0.0,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Ametista",
            "corretor": "Thati",
            "leads": 0,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-05-21",
              "end": "2026-06-20",
              "days_active": 7,
              "days_left": 23,
              "start_label": "21/05/26",
              "end_label": "20/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Ametista | Thati",
              "spend": 0.0,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Horto Boulevard",
            "corretor": "Dimitry",
            "leads": 0,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-05-28",
              "end": "2026-06-27",
              "days_active": 0,
              "days_left": 30,
              "start_label": "28/05/26",
              "end_label": "27/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Horto Boulevard | Dimitry",
              "spend": 0.0,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Aquasol",
            "corretor": "Yohanna",
            "leads": 0,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-05-21",
              "end": "2026-06-20",
              "days_active": 7,
              "days_left": 23,
              "start_label": "21/05/26",
              "end_label": "20/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Aquasol | Yohanna",
              "spend": 0.0,
              "spend_shared": false
            }
          }
        ],
        "motivos": [
          {
            "label": "Não responde / não atende",
            "value": 53,
            "pct": 57.0
          },
          {
            "label": "Motivo ambíguo (revisar)",
            "value": 22,
            "pct": 23.7
          },
          {
            "label": "Lead repetido",
            "value": 4,
            "pct": 4.3
          },
          {
            "label": "Sem motivo registrado",
            "value": 3,
            "pct": 3.2
          },
          {
            "label": "Não gostou do imóvel/região",
            "value": 3,
            "pct": 3.2
          },
          {
            "label": "Valor / orçamento",
            "value": 3,
            "pct": 3.2
          },
          {
            "label": "Lead inválido",
            "value": 3,
            "pct": 3.2
          },
          {
            "label": "Comprou com concorrente",
            "value": 2,
            "pct": 2.2
          }
        ],
        "motivos_total": 93,
        "perdas_by_emp": [
          {
            "emp": "Edf. Greco",
            "corretor": "Rose",
            "perdas": 61,
            "motivos": {
              "Motivo ambíguo (revisar)": 16,
              "Não responde / não atende": 39,
              "Valor / orçamento": 3,
              "Comprou com concorrente": 2,
              "Não gostou do imóvel/região": 1
            }
          },
          {
            "emp": "Casa no Antares",
            "corretor": "Gedson",
            "perdas": 16,
            "motivos": {
              "Sem motivo registrado": 2,
              "Não gostou do imóvel/região": 1,
              "Não responde / não atende": 9,
              "Motivo ambíguo (revisar)": 1,
              "Lead repetido": 3
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Guilherme",
            "perdas": 5,
            "motivos": {
              "Não gostou do imóvel/região": 1,
              "Não responde / não atende": 1,
              "Motivo ambíguo (revisar)": 3
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Fernanda",
            "perdas": 4,
            "motivos": {
              "Lead inválido": 3,
              "Não responde / não atende": 1
            }
          },
          {
            "emp": "Edf. Jorge",
            "corretor": "Tatiana",
            "perdas": 3,
            "motivos": {
              "Lead repetido": 1,
              "Não responde / não atende": 2
            }
          },
          {
            "emp": "Edf. Guaxuma",
            "corretor": "Fernanda",
            "perdas": 2,
            "motivos": {
              "Não responde / não atende": 1,
              "Motivo ambíguo (revisar)": 1
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Nath",
            "perdas": 1,
            "motivos": {
              "Motivo ambíguo (revisar)": 1
            }
          },
          {
            "emp": "Jatiúca",
            "corretor": "Adriana",
            "perdas": 1,
            "motivos": {
              "Sem motivo registrado": 1
            }
          }
        ],
        "series": {
          "labels": [
            "01/04",
            "02/04",
            "03/04",
            "04/04",
            "05/04",
            "06/04",
            "07/04",
            "08/04",
            "09/04",
            "10/04",
            "11/04",
            "12/04",
            "13/04",
            "14/04",
            "15/04",
            "16/04",
            "17/04",
            "18/04",
            "19/04",
            "20/04",
            "21/04",
            "22/04",
            "23/04",
            "24/04",
            "25/04",
            "26/04",
            "27/04",
            "28/04",
            "29/04",
            "30/04"
          ],
          "total": [
            6,
            3,
            6,
            5,
            10,
            11,
            8,
            6,
            3,
            3,
            1,
            0,
            4,
            1,
            1,
            27,
            3,
            8,
            7,
            7,
            7,
            2,
            6,
            2,
            2,
            5,
            3,
            4,
            12,
            6
          ],
          "perda": [
            5,
            2,
            4,
            1,
            6,
            7,
            8,
            3,
            2,
            1,
            1,
            0,
            4,
            1,
            1,
            18,
            3,
            4,
            3,
            5,
            5,
            1,
            1,
            1,
            0,
            2,
            1,
            1,
            0,
            2
          ],
          "atend": [
            0,
            0,
            1,
            3,
            4,
            1,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            6,
            0,
            3,
            2,
            0,
            0,
            1,
            5,
            1,
            2,
            1,
            1,
            2,
            10,
            4
          ],
          "visita": [
            0,
            0,
            1,
            0,
            0,
            1,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            1,
            1,
            0,
            0,
            0
          ],
          "qual": [
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "proposta": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        }
      },
      "meta": {
        "spend": 1655.57,
        "impressions": 66443,
        "clicks": 1554,
        "ctr": 2.34,
        "frequency": 2.52,
        "reach": 26405,
        "leads_form": 147,
        "msg_started": 14,
        "total_meta": 161,
        "cpl": 10.28,
        "campaign": {
          "name": "Fundo de Funil | Blend Grand Reserva | 12/05 #TP",
          "status": "ACTIVE",
          "label": "Ativa",
          "start_time": "2026-05-12T19:26:06-0300",
          "objective": "OUTCOME_LEADS"
        }
      },
      "plan": [
        {
          "tag": "Prioridade alta",
          "cls": "crit",
          "icon": "alert",
          "title": "Resgatar a base não respondida",
          "desc": "<b>53 leads</b> do período entraram e não retornaram contato. Antes de aumentar volume, rodar uma cadência de reengajamento e revisar tempo médio de primeiro toque. <b>Maior ponto de alavancagem do mês.</b>"
        },
        {
          "tag": "Time comercial",
          "cls": "proc",
          "icon": "team",
          "title": "Sensia, calibrar distribuição",
          "desc": "3 corretores no mesmo produto. A <b>única proposta do período saiu daqui</b>, o produto tem demanda. Revisar como leads são distribuídos e padronizar a abordagem pode acelerar o ciclo."
        },
        {
          "tag": "Processo",
          "cls": "proc",
          "icon": "process",
          "title": "Padronizar planilhas",
          "desc": "<b>4% dos leads sem status</b> (6 leads). Definir status obrigatório e motivo de perda destrava a próxima camada de análise por produto."
        }
      ]
    },
    "maio": {
      "period": {
        "start": "2026-05-01",
        "end": "2026-05-28",
        "label": "01/05 a 28/05",
        "name": "Maio"
      },
      "stats": {
        "totals": {
          "em_atendimento": 26,
          "desqualificado": 13,
          "sem_status": 60,
          "proposta": 1,
          "visita": 3,
          "qualificado": 1,
          "outros_produtos": 1
        },
        "n_total": 105,
        "perdidos": 13,
        "pct_perda": 12.4,
        "empreend": [
          {
            "emp": "Edf. Paradise Beach",
            "corretor": "Gedson",
            "leads": 21,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 1,
            "perda": 0,
            "outros": 0,
            "sem": 20,
            "timing": {
              "start": "2026-05-22",
              "end": "2026-06-21",
              "days_active": 6,
              "days_left": 24,
              "start_label": "22/05/26",
              "end_label": "21/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Paradise Beach | Gedson",
              "spend": 182.95,
              "spend_shared": false
            }
          },
          {
            "emp": "Jatiúca",
            "corretor": "Adriana",
            "leads": 21,
            "atend": 10,
            "visita": 1,
            "qual": 0,
            "proposta": 0,
            "perda": 7,
            "outros": 1,
            "sem": 2,
            "timing": {
              "start": "2026-04-27",
              "end": "2026-05-27",
              "days_active": 31,
              "days_left": -1,
              "start_label": "27/04/26",
              "end_label": "27/05/26",
              "ad_status": "PAUSED",
              "ad_name": "Jatiúca | Adriana",
              "spend": 460.48,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Fernanda",
            "leads": 10,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 10,
            "timing": {
              "start": "2026-02-27",
              "end": "2026-03-29",
              "days_active": 90,
              "days_left": -60,
              "start_label": "27/02/26",
              "end_label": "29/03/26",
              "ad_status": "PAUSED",
              "ad_name": "Sensia | Nath/Guilherme/Fernanda",
              "spend": 361.81,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Guilherme",
            "leads": 10,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 10,
            "timing": {
              "start": "2026-02-27",
              "end": "2026-03-29",
              "days_active": 90,
              "days_left": -60,
              "start_label": "27/02/26",
              "end_label": "29/03/26",
              "ad_status": "PAUSED",
              "ad_name": "Sensia | Nath/Guilherme/Fernanda",
              "spend": 361.81,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Sensia",
            "corretor": "Nath",
            "leads": 10,
            "atend": 8,
            "visita": 1,
            "qual": 1,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-02-27",
              "end": "2026-03-29",
              "days_active": 90,
              "days_left": -60,
              "start_label": "27/02/26",
              "end_label": "29/03/26",
              "ad_status": "PAUSED",
              "ad_name": "Sensia | Nath/Guilherme/Fernanda",
              "spend": 361.81,
              "spend_shared": false
            }
          },
          {
            "emp": "Casa no Antares",
            "corretor": "Gedson",
            "leads": 6,
            "atend": 1,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 1,
            "outros": 0,
            "sem": 4,
            "timing": {
              "start": "2026-04-01",
              "end": "2026-05-01",
              "days_active": 57,
              "days_left": -27,
              "start_label": "01/04/26",
              "end_label": "01/05/26",
              "ad_status": "PAUSED",
              "ad_name": "Casa no Antares | Gedson",
              "spend": 111.61,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Greco",
            "corretor": "Rose",
            "leads": 6,
            "atend": 1,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 3,
            "outros": 0,
            "sem": 2,
            "timing": {
              "start": "2026-04-01",
              "end": "2026-05-01",
              "days_active": 57,
              "days_left": -27,
              "start_label": "01/04/26",
              "end_label": "01/05/26",
              "ad_status": "PAUSED",
              "ad_name": "Edf. Greco | Rose",
              "spend": 69.67,
              "spend_shared": false
            }
          },
          {
            "emp": "Blend Grand Reserva",
            "corretor": "Stefan",
            "leads": 5,
            "atend": 3,
            "visita": 1,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 1,
            "timing": {
              "start": "2026-05-22",
              "end": "2026-06-21",
              "days_active": 6,
              "days_left": 24,
              "start_label": "22/05/26",
              "end_label": "21/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "VD01",
              "spend": 0.0,
              "spend_shared": false
            }
          },
          {
            "emp": "Blend Grand Reserva",
            "corretor": "Marcos Jr",
            "leads": 4,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 4,
            "timing": {
              "start": "2026-05-22",
              "end": "2026-06-21",
              "days_active": 6,
              "days_left": 24,
              "start_label": "22/05/26",
              "end_label": "21/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "VD01",
              "spend": 0.0,
              "spend_shared": false
            }
          },
          {
            "emp": "Blend Grand Reserva",
            "corretor": "Tati",
            "leads": 3,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 1,
            "outros": 0,
            "sem": 2,
            "timing": {
              "start": "2026-05-22",
              "end": "2026-06-21",
              "days_active": 6,
              "days_left": 24,
              "start_label": "22/05/26",
              "end_label": "21/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "VD01",
              "spend": 0.0,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Ametista",
            "corretor": "Thati",
            "leads": 3,
            "atend": 1,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 1,
            "outros": 0,
            "sem": 1,
            "timing": {
              "start": "2026-05-21",
              "end": "2026-06-20",
              "days_active": 7,
              "days_left": 23,
              "start_label": "21/05/26",
              "end_label": "20/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Ametista | Thati",
              "spend": 23.81,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Jorge",
            "corretor": "Tatiana",
            "leads": 2,
            "atend": 2,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-04-01",
              "end": "2026-05-01",
              "days_active": 57,
              "days_left": -27,
              "start_label": "01/04/26",
              "end_label": "01/05/26",
              "ad_status": "PAUSED",
              "ad_name": "Edf. Jorge | Tatiana",
              "spend": 4.5,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Horto Boulevard",
            "corretor": "Dimitry",
            "leads": 2,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 2,
            "timing": {
              "start": "2026-05-28",
              "end": "2026-06-27",
              "days_active": 0,
              "days_left": 30,
              "start_label": "28/05/26",
              "end_label": "27/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Horto Boulevard | Dimitry",
              "spend": 11.13,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Guaxuma",
            "corretor": "Fernanda",
            "leads": 1,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 1,
            "timing": {
              "start": "2026-04-30",
              "end": "2026-05-30",
              "days_active": 28,
              "days_left": 2,
              "start_label": "30/04/26",
              "end_label": "30/05/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Guaxuma | Fernanda",
              "spend": 99.9,
              "spend_shared": false
            }
          },
          {
            "emp": "Edf. Aquasol",
            "corretor": "Yohanna",
            "leads": 1,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 1,
            "timing": {
              "start": "2026-05-21",
              "end": "2026-06-20",
              "days_active": 7,
              "days_left": 23,
              "start_label": "21/05/26",
              "end_label": "20/06/26",
              "ad_status": "ACTIVE",
              "ad_name": "Edf. Aquasol | Yohanna",
              "spend": 41.78,
              "spend_shared": false
            }
          },
          {
            "emp": "JTR Jatiúca",
            "corretor": "Nathalia",
            "leads": 0,
            "atend": 0,
            "visita": 0,
            "qual": 0,
            "proposta": 0,
            "perda": 0,
            "outros": 0,
            "sem": 0,
            "timing": {
              "start": "2026-04-27",
              "end": "2026-05-27",
              "days_active": 31,
              "days_left": -1,
              "start_label": "27/04/26",
              "end_label": "27/05/26",
              "ad_status": "PAUSED",
              "ad_name": "JTR Jatiúca | Nathalia",
              "spend": 6.4,
              "spend_shared": false
            }
          }
        ],
        "motivos": [
          {
            "label": "Sem motivo registrado",
            "value": 8,
            "pct": 61.5
          },
          {
            "label": "Não responde / não atende",
            "value": 3,
            "pct": 23.1
          },
          {
            "label": "Motivo ambíguo (revisar)",
            "value": 2,
            "pct": 15.4
          }
        ],
        "motivos_total": 13,
        "perdas_by_emp": [
          {
            "emp": "Jatiúca",
            "corretor": "Adriana",
            "perdas": 7,
            "motivos": {
              "Sem motivo registrado": 7
            }
          },
          {
            "emp": "Edf. Greco",
            "corretor": "Rose",
            "perdas": 3,
            "motivos": {
              "Não responde / não atende": 3
            }
          },
          {
            "emp": "Casa no Antares",
            "corretor": "Gedson",
            "perdas": 1,
            "motivos": {
              "Motivo ambíguo (revisar)": 1
            }
          },
          {
            "emp": "Blend Grand Reserva",
            "corretor": "Tati",
            "perdas": 1,
            "motivos": {
              "Motivo ambíguo (revisar)": 1
            }
          },
          {
            "emp": "Edf. Ametista",
            "corretor": "Thati",
            "perdas": 1,
            "motivos": {
              "Sem motivo registrado": 1
            }
          }
        ],
        "series": {
          "labels": [
            "01/05",
            "02/05",
            "03/05",
            "04/05",
            "05/05",
            "06/05",
            "07/05",
            "08/05",
            "09/05",
            "10/05",
            "11/05",
            "12/05",
            "13/05",
            "14/05",
            "15/05",
            "16/05",
            "17/05",
            "18/05",
            "19/05",
            "20/05",
            "21/05",
            "22/05",
            "23/05",
            "24/05",
            "25/05",
            "26/05",
            "27/05",
            "28/05"
          ],
          "total": [
            4,
            0,
            4,
            4,
            8,
            0,
            6,
            5,
            3,
            0,
            4,
            4,
            5,
            2,
            4,
            4,
            3,
            2,
            4,
            1,
            5,
            4,
            1,
            0,
            22,
            1,
            1,
            4
          ],
          "perda": [
            2,
            0,
            2,
            1,
            2,
            0,
            2,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "atend": [
            1,
            0,
            1,
            2,
            4,
            0,
            3,
            2,
            0,
            0,
            1,
            1,
            2,
            1,
            0,
            0,
            1,
            2,
            2,
            0,
            1,
            1,
            0,
            0,
            1,
            0,
            0,
            0
          ],
          "visita": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "qual": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "proposta": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0
          ]
        }
      },
      "meta": {
        "spend": 1862.71,
        "impressions": 47483,
        "clicks": 921,
        "ctr": 1.94,
        "frequency": 3.25,
        "reach": 14616,
        "leads_form": 104,
        "msg_started": 13,
        "total_meta": 117,
        "cpl": 15.92,
        "campaign": {
          "name": "Fundo de Funil | Blend Grand Reserva | 12/05 #TP",
          "status": "ACTIVE",
          "label": "Ativa",
          "start_time": "2026-05-12T19:26:06-0300",
          "objective": "OUTCOME_LEADS"
        }
      },
      "plan": [
        {
          "tag": "Time comercial",
          "cls": "proc",
          "icon": "team",
          "title": "Sensia, calibrar distribuição",
          "desc": "3 corretores no mesmo produto. A <b>única proposta do período saiu daqui</b>, o produto tem demanda. Revisar como leads são distribuídos e padronizar a abordagem pode acelerar o ciclo."
        },
        {
          "tag": "Processo",
          "cls": "proc",
          "icon": "process",
          "title": "Padronizar planilhas",
          "desc": "<b>57% dos leads sem status</b> (60 leads). Definir status obrigatório e motivo de perda destrava a próxima camada de análise por produto."
        }
      ]
    }
  }
};
