window.NI_DATA = {
  "period": {
    "start": "2026-04-01",
    "end": "2026-05-04",
    "label": "01/04 a 04/05"
  },
  "generated_at": "06/05/2026 03:12",
  "stats": {
    "totals": {
      "desqualificado": 97,
      "em_atendimento": 46,
      "qualificado": 6,
      "visita": 6,
      "sem_status": 20,
      "outros_produtos": 9,
      "nao_momento": 1
    },
    "n_total": 185,
    "perdidos": 97,
    "pct_perda": 52.4,
    "empreend": [
      {
        "emp": "Edf. Greco",
        "corretor": "Rose",
        "leads": 96,
        "atend": 15,
        "visita": 3,
        "qual": 3,
        "proposta": 0,
        "perda": 64,
        "outros": 8,
        "sem": 3
      },
      {
        "emp": "Casa no Antares",
        "corretor": "Gedson",
        "leads": 27,
        "atend": 6,
        "visita": 1,
        "qual": 1,
        "proposta": 0,
        "perda": 16,
        "outros": 0,
        "sem": 3
      },
      {
        "emp": "Edf. Sensia",
        "corretor": "Guilherme",
        "leads": 17,
        "atend": 10,
        "visita": 0,
        "qual": 0,
        "proposta": 0,
        "perda": 5,
        "outros": 2,
        "sem": 0
      },
      {
        "emp": "Edf. Guaxuma",
        "corretor": "Fernanda",
        "leads": 11,
        "atend": 7,
        "visita": 0,
        "qual": 0,
        "proposta": 0,
        "perda": 4,
        "outros": 0,
        "sem": 0
      },
      {
        "emp": "Jatiúca",
        "corretor": "Adriana",
        "leads": 11,
        "atend": 2,
        "visita": 0,
        "qual": 0,
        "proposta": 0,
        "perda": 0,
        "outros": 0,
        "sem": 9
      },
      {
        "emp": "Edf. Jorge",
        "corretor": "Tatiana",
        "leads": 7,
        "atend": 1,
        "visita": 0,
        "qual": 0,
        "proposta": 0,
        "perda": 3,
        "outros": 0,
        "sem": 3
      },
      {
        "emp": "Edf. Sensia",
        "corretor": "Fernanda",
        "leads": 7,
        "atend": 2,
        "visita": 1,
        "qual": 0,
        "proposta": 0,
        "perda": 4,
        "outros": 0,
        "sem": 0
      },
      {
        "emp": "Edf. Sensia",
        "corretor": "Nath",
        "leads": 7,
        "atend": 3,
        "visita": 1,
        "qual": 2,
        "proposta": 0,
        "perda": 1,
        "outros": 0,
        "sem": 0
      },
      {
        "emp": "JTR Jatiúca",
        "corretor": "Nathalia",
        "leads": 2,
        "atend": 0,
        "visita": 0,
        "qual": 0,
        "proposta": 0,
        "perda": 0,
        "outros": 0,
        "sem": 2
      }
    ],
    "motivos": [
      {
        "label": "Não responde / não atende",
        "value": 56,
        "pct": 57.7
      },
      {
        "label": "Motivo ambíguo (revisar)",
        "value": 23,
        "pct": 23.7
      },
      {
        "label": "Lead repetido",
        "value": 4,
        "pct": 4.1
      },
      {
        "label": "Sem motivo registrado",
        "value": 3,
        "pct": 3.1
      },
      {
        "label": "Não gostou do imóvel/região",
        "value": 3,
        "pct": 3.1
      },
      {
        "label": "Valor / orçamento",
        "value": 3,
        "pct": 3.1
      },
      {
        "label": "Lead inválido",
        "value": 3,
        "pct": 3.1
      },
      {
        "label": "Comprou com concorrente",
        "value": 2,
        "pct": 2.1
      }
    ],
    "motivos_total": 97,
    "series": {
      "labels": [
        "01/04",
        "02/04",
        "03/04",
        "04/04",
        "05/04",
        "06/04",
        "07/04",
        "08/04",
        "09/04",
        "10/04",
        "11/04",
        "12/04",
        "13/04",
        "14/04",
        "15/04",
        "16/04",
        "17/04",
        "18/04",
        "19/04",
        "20/04",
        "21/04",
        "22/04",
        "23/04",
        "24/04",
        "25/04",
        "26/04",
        "27/04",
        "28/04",
        "29/04",
        "30/04",
        "01/05",
        "02/05",
        "03/05",
        "04/05"
      ],
      "total": [
        6,
        3,
        6,
        5,
        10,
        11,
        8,
        6,
        3,
        3,
        1,
        0,
        4,
        1,
        1,
        27,
        3,
        8,
        7,
        7,
        7,
        4,
        6,
        2,
        2,
        5,
        5,
        4,
        12,
        6,
        4,
        0,
        4,
        4
      ],
      "perda": [
        5,
        2,
        4,
        1,
        6,
        7,
        8,
        3,
        2,
        1,
        1,
        0,
        4,
        1,
        1,
        18,
        3,
        4,
        3,
        5,
        5,
        3,
        1,
        1,
        0,
        2,
        1,
        1,
        0,
        1,
        0,
        0,
        2,
        1
      ],
      "atend": [
        0,
        0,
        1,
        3,
        4,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        6,
        0,
        3,
        2,
        0,
        0,
        1,
        5,
        1,
        2,
        1,
        1,
        1,
        6,
        4,
        1,
        0,
        1,
        1
      ],
      "visita": [
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "qual": [
        0,
        0,
        1,
        0,
        0,
        1,
        0,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
        1,
        1,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ],
      "proposta": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    }
  },
  "meta": {
    "spend": 1888.18,
    "spend_fmt": "R$ 1.888,18",
    "impressions": 74854,
    "clicks": 1731,
    "ctr": 2.31,
    "frequency": 2.68,
    "reach": 27893,
    "leads_form": 164,
    "msg_started": 15,
    "total_meta": 179,
    "cpl": 10.55
  },
  "plan": [
    {
      "tag": "Prioridade alta",
      "cls": "crit",
      "icon": "alert",
      "title": "Resgatar a base não respondida",
      "desc": "<b>56 leads</b> do período entraram e não retornaram contato. Antes de aumentar volume, rodar uma cadência de reengajamento e revisar tempo médio de primeiro toque. <b>Maior ponto de alavancagem do mês.</b>"
    },
    {
      "tag": "Time comercial",
      "cls": "proc",
      "icon": "team",
      "title": "Sensia, calibrar distribuição",
      "desc": "3 corretores no mesmo produto. A <b>única proposta do mês saiu daqui</b>, o produto tem demanda. Revisar como leads são distribuídos e padronizar a abordagem pode acelerar o ciclo."
    },
    {
      "tag": "Processo",
      "cls": "proc",
      "icon": "process",
      "title": "Padronizar planilhas",
      "desc": "<b>11% dos leads sem status</b> (20 leads). Definir status obrigatório e motivo de perda destrava a próxima camada de análise por produto."
    }
  ]
};
